apiVersion: 1

policies:
  - orgId: 1
    receiver: noop-dev
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - matcher: severity="critical"
        receiver: consultor-ia-critical
        group_wait: 0s
        group_interval: 1m
        repeat_interval: 15m
      - matcher: severity="warning"
        receiver: consultor-ia-warning
        group_wait: 1m
        group_interval: 5m
        repeat_interval: 2h
